# Generated by Django 5.0.6 on 2024-06-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='position',
            field=models.CharField(default='CEO', max_length=50),
        ),
    ]
